### ISSUE TITLE
Плагин отображает файлы только с одинаковым префиксом

### ISSUE THREAD

**Issue by dimensi** [artdevue/FileDir#9]
Здравствуйте, вы написали очень удобный плагин, но у меня есть проблема. Я использую его, чтоб вызывать по порядку изображения для слайдера. Я назвал первые 5 файлов img-slider-1,img-slider-2... img-slider-5 и теперь когда я заливаю в папку файл  с рандомным названием, то у меня он не отображается, но если я его переименовываю аналогично в img-slider-6, то он начинает и этот отображать.  В чем дело?  Может я какую-ту надстройку упустил?

**Comment by DrSatyr** [comment]
Чет Вы явно не правильно сделали: http://take.ms/s0FL3 вот для теста у себя переименовал, все ОК, сортировка поменялась только... так что это явно не баг :)

**Comment by dimensi** [comment]
@DrSatyr Да вы правы, это была моя глупость, я почему-то не додумался очистить кеш сайта. Проблема решена. Извиняюсь, за поднятие темы.
